name: Update data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '13 3,9 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: gspread credentials 1
        run: |
          mkdir .config
          mkdir .config/gspread
          pwd
          ls
      - name: gspread credentials 2
        uses: jsdaniell/create-json@1.1.2
        with:
          name: 'service_account.json'
          json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          dir: '.config/gspread/'
      - name: gspread 3
        run: |
          cd .config/gspread
          pwd
          ls
          cat service_account.json
          echo '***'
          cat ${{ secrets.SERVICE_ACCOUNT_JSON }}
          echo 'xxx'
          echo ${{ secrets.SERVICE_ACCOUNT_JSON }}
      
      - name: Update Autria 
        run: python scripts/austria.py "/home/runner/work/covid-europe/covid-europe/.config/gspread/service_account.json"
      - name: Update Germany 
        run: python scripts/germany.py
      - name: Update Poland 
        run: python scripts/poland.py
      - name: Update Slovakia
        run: python scripts/slovakia.py
      
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
